services:
  - type: web
    name: checkmate-dsat
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python preprocess_pipeline.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
