services:
services:
  - type: web
    name: dsat
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python preprocess_pipeline.py
    startCommand: bash -c "source .venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
